---
# tasks file for ansible-role-gitlab-runner
- name: Download gitlab-runner installer
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-ci-multi-runner/script.deb.sh
    dest: /tmp/script-runner.deb.sh
    mode: 0770
  tags:
    - gitlab-runner.install

- name: Execute gitlab installer >> /.gitlab-runner-installer.log
  shell: /tmp/script-runner.deb.sh
  become: true
  args:
    creates: /.gitlab-runner-installer.log
  tags:
    - gitlab-runner.install
- name: Install gitlab runner
  apt: name=gitlab-ci-multi-runner state=present
  become: true
  tags:
    - gitlab-runner.install
