---
- name: Register gitlab runner 
  shell: gitlab-ci-multi-runner register --registration-token {{ gitlab_runner_registration_token|quote }} --name {{ gitlab_runner_name|quote }} --url {{ gitlab_runner_url|quote }} --executor {{ gitlab_runner_executor|quote }} --non-interactive
  args:
    creates: /.runner-{{ gitlab_runner_name|hash('md5') }}
    chdir: /tmp/
  tags:
    - gitlab-runner.registration
